# Generated by Django 3.2.9 on 2021-11-28 04:44

from django.db import migrations, models
import django.db.models.deletion
import school.enums


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_student_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('MORNING', 'MORNING'), ('AFTERNOON', 'AFTERNOON'), ('NIGHT', 'NIGHT')], default=school.enums.EnrolmentPeriodEnum['MORNING'], max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
            ],
        ),
    ]
